#include <iostream>
#include <vector>
#include <list>
using namespace std;





//PASO 1: LIMPIAR FRASES Y DESPUES HACER LOWER CASE 
//PASO 2: QUITAR STOP WORDS
//PASO 3: ROTAR (TODAS LAS PERMUTACIONES)
//PASO 4: ORDENAR SEGUN ORDENAMIENTO INDICADO
